version: '3.9'

services:
  postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cospworld
      POSTGRES_USER: cospworld
      POSTGRES_PASSWORD: cospworld
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local